apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-docker-image-from-git-source-task-run-java
spec:
  serviceAccountName: tutorial-service
  taskRef:
    name: build-docker-image-from-git-source-java
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: skaffold-git
    params:
      - name: pathToDockerFile
        value: Dockerfile.multistage
      - name: pathToContext
        value: /workspace/docker-source #configure: may change according to your source
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: skaffold-image-leeroy-web
